config/routes.rb
# require "stripe_event"
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :users
  root to: "donation_types#index"
  get "about", to: "about#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :baskets, only: %i[show update create] do
    resources :payments, only: %i[new show]
    resources :basket_items, only: %i[create update destroy]
    # get :checkout, on: :member
  end
  get "/basket_items/unredeemed_items", to: "basket_items#unredeemed_items", as: "unredeemed_items"
  resources :charity_profiles do
    resources :donation_types
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user, optional: true
  store :guest_user, accessors: %i[email first_name last_name phone_number], prefix: true, coder: JSON
  has_many :basket_items, dependent: :destroy
  has_many :donation_types, through: :basket_items
  monetize :amount_cents

  def guest?
    user.nil? && guest_user.present?
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :find_basket, only: %i[update show]

  def create
    @basket = Basket.find(params[:basket_id])
    authorize @basket
    if @basket.nil?
      redirect_to root_path, status: :unprocessable_entity
    else
      user = current_user if current_user
      @basket.user = user
      items = BasketItem.where(basket_id: @basket.id)
      line_items_data = {}
      line_items_array = []
      items.each do |item|
        line_items_array << line_items_data = {
          price_data: {
            currency: 'gbp',
            unit_amount: item.donation_type.price_cents,
            product_data: {
              name: item.donation_type.name
            }
          },
          quantity: 1
        }
      end
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: line_items_array,
        mode: "payment",
        success_url: basket_payment_url(@basket, @basket),
        cancel_url: basket_url(@basket)
      )
      price_total = []
      line_items_array.each do |hash|
        price_total << hash[:price_data][:unit_amount]
      end
      @basket.update(checkout_session_id: session.id, amount_cents: price_total.sum, state: 'pending')
      redirect_to new_basket_payment_path(@basket)
    end
  end

  def show
    authorize @basket
  end

  def update
    skip_authorization
    @basket.update(guest_user: guest_basket_params)
    if @basket.nil?
      redirect_to root_path, status: :unprocessable_entity
    else
      items = BasketItem.where(basket_id: @basket.id)
      line_items_data = {}
      line_items_array = []
      items.each do |item|
        line_items_array << line_items_data = {
          price_data: {
            currency: 'gbp',
            unit_amount: item.donation_type.price_cents,
            product_data: {
              name: item.donation_type.name
            }
          },
          quantity: 1
        }
      end
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: line_items_array,
        mode: "payment",
        success_url: basket_payment_url(@basket, @basket),
        cancel_url: basket_url(@basket)
      )
      price_total = []
      line_items_array.each do |hash|
        price_total << hash[:price_data][:unit_amount]
      end
      @basket.update(checkout_session_id: session.id, amount_cents: price_total.sum, state: 'pending')
      redirect_to new_basket_payment_path(@basket)
    end
  end

  # def checkout
  #   authorize @basket
  #   session[:basket_id] = nil
  # end

  private

  def find_basket
    @basket = Basket.find(params[:id])
  end

  def guest_basket_params
    params.require(:guest_basket).permit(:email, :first_name, :last_name, :phone_number)
  end
end

app/views/baskets/show.html.erb
<div class="checkcont">
    <div>
      <h1 class="page-title">Your Basket</h1>
      <br>
       <h5>Update your cart or proceed to checkout</h5>
        <hr>
          <%# <ul style="list-style: none; font: size 20px;"> %>
          <% @basket.basket_items.each do |item| %>
              <li>
                <div class="bitems">
                  <img class="bimg" src="<%= image_path item.donation_type.photo_url %>">
                  <div class="btext"><%= item.donation_type.name %> - £<%= item.donation_type.price %></div>
                    <div class="bicon"><%= link_to basket_basket_item_path(item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: "color: black; margin: left;"  do %>
                    <i class="fa-regular fa-trash-can"></i>
                    <% end %>
                    </div>
                  </div>
                </li>
            <%end %>
          <%# </ul> %>
        <hr>
      </div>

  <div class="b-button-container">
    <% if current_user.nil? %>
    <div class="btn-orange-rounded" data-bs-toggle="modal" data-bs-target="#guestModal">Guest Checkout</div>
    <div class="modal custom fade" id="guestModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content" style="background: #8EB8E5;" >
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Guest Checkout</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for :guest_basket, url: basket_path(@basket), method: :patch do |f| %>
            <%= f.input :email %>
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <%= f.input :phone_number %>
            <%= f.submit 'Checkout', class: "btn-orange-rounded" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="btn-orange-rounded" data-bs-toggle="modal" data-bs-target="#createModal">Create Account</div>
    <div class="modal custom fade" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content" style="background: #8EB8E5;" >
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Create an account</h1></h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), data: { turbo: :false }) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :email,
                          required: true,
                          autofocus: true,
                          placeholder: "bob@gmail.com",
                          input_html: { autocomplete: "email" }%>
              <%= f.input :password,
                          required: true,
                          placeholder: "••••••",
                          hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                          input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                          required: true,
                          placeholder: "••••••",
                          input_html: { autocomplete: "new-password" } %>
                          <%= f.input :first_name %>
                          <%= f.input :last_name %>
                          <%= f.input :address %>
                          <%= f.input :phone_number %>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Sign up", class:"btn-orange-rounded" %>
            </div>
            <% end %>
            <%# <%= render "devise/shared/links" %>
          </div>
        </div>

    <% elsif !current_user.charity %>
          <%= form_with url: baskets_path do %>
          <%= hidden_field_tag 'basket_id', @basket.id %>
          <%= submit_tag 'View Final Donation', class: 'btn-orange-rounded', style:"width: 300px" %>
        <% end %>

      </div>


    <% end %>