config/routes.rb
# require "stripe_event"
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :users
  root to: "donation_types#index"
  get "about", to: "about#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :baskets, only: %i[show update create] do
    resources :payments, only: %i[new show]
    resources :basket_items, only: %i[create update destroy]
    # get :checkout, on: :member
  end
  get "/basket_items/unredeemed_items", to: "basket_items#unredeemed_items", as: "unredeemed_items"
  resources :charity_profiles do
    resources :donation_types
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/controllers/donation_types_controller.rb
class DonationTypesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    # THIS IS THE CODE WHERE THE BASKET IS BEING INSTANTIATED - NOT IN BASKET CONTROLLER
    @donationtypes = DonationType.where(active: true)
    @basket_item = BasketItem.new
    @charity_profile = CharityProfile.find(@user.id) if !@user.nil? && @user.charity
    basket_id = session[:basket_id]
    @unredeeemed_donations = BasketItem.includes(:basket, :donation_type).where(redeemed: false, baskets: { state: 'paid' })
    @basket = Basket.find_by(id: basket_id)
    if current_user.nil? || !current_user.charity
      @user = current_user unless current_user.nil?
      if @basket.nil?
        @basket = Basket.new
        @basket.user = current_user if current_user
        session[:basket_id] = @basket.id if @basket.save
      end
    else
      @user = current_user
      if @basket.nil?
        @basket = Basket.new
        @basket.user = @user
        session[:basket_id] = @basket.id if @basket.save
      end
    end
  end

  # def show
  #   authorize @donationtype
  #   # user = current_user
  #   # charity = CharityProfile.find(user.id)
  #   @donationtype = DonationType.find(params[:id])
  # end

  def new
    @donationtype = DonationType.new
    authorize @donationtype
  end

  def create
    authorize @donationtype
    @donationtype = DonationType.new(donationtype_params)
    if @donationtype.save!
      redirect_to user_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @donationtype = DonationType.find(params[:charity_profile_id])
    authorize @donationtype
  end

  def update
    @donationtype = DonationType.find(params[:id])
    authorize @donationtype
    @user = current_user
    if @donationtype.update(donationtype_params)
      flash.notice = "Donation status updated"
      redirect_to user_path(@user)
    else
      flash.alert = "Unable to update"
      render user_path(@user)
    end
  end

  def destroy
    authorize @donationtype
    @donationtype = DonationType.find(params[:id])
    @donationtype.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def donationtype_params
    params.require(:donation_type).permit(:active)
  end
end

app/views/donation_types/index.html.erb
<div class = "header-section">
  <h1 class="page-title">The Giving Loop</h1>
  <p class="body-text">Closing the feedback loop on charitable donations for the homeless</p>
</div>

<% if @user.nil? || !@user.charity %>
  <div class = "info-icon" >
    <%= link_to about_path do %>
    <%= image_tag "InfoIcon.png", style:"margin-top: 5px; margin-right: 5px;", class: "nav-bar-icon-images" %>
    <% end %>
  </div>

  <div class="card-container">
    <% @donationtypes.each do |donationtype| %>
      <div class="flip-card" onclick="this.classList.toggle('flipped')">
        <div class="card-inner">
          <div class="card-front">
            <%= image_tag donationtype.photo_url %>
              <li class="card-front-title"><%= donationtype.name %>  <i class="fa-solid fa-circle-info"></i> </li>
              <li class="card-price"><%= humanized_money_with_symbol(donationtype.price) %></li>
              <%= simple_form_for [ @basket, @basket_item ] do |f| %>
                <%= f.hidden_field :donation_type_id, value: donationtype.id %>
                <div class="card-button">
                  <%= f.submit "Add To Basket", class: "btn-orange-card-rounded", onclick: "event.stopPropagation();" %>
                </div>
              <% end %>
          </div>

          <div class="card-back"><%= donationtype.bio %>
            <li class="card-back-title"><%= donationtype.name %> - <%= humanized_money_with_symbol(donationtype.price) %></li>
            <%= simple_form_for [ @basket, @basket_item ] do |f| %>
              <%= f.hidden_field :donation_type_id, value: donationtype.id %>
                <div class="card-button">
                  <%= f.submit "Add To Basket", class: "btn-orange-card-rounded", onclick: "event.stopPropagation();" %>
                </div>
              <% end %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
<% end %>


<% if !@user.nil? && @user.charity %>
  <div class="invent">
    <% price = [] %>
    <h1>Welcome <%= @user.first_name %>,</h1>
    <br>
    <h5>Below is a summary of donations available to redeem:</h5>
    <br>
    <h2>Donation Inventory</h2>
    <% @unredeeemed_donations.each do |item| %>
      <% price << item.donation_type.price %>
    <% end %>
    <h5>Unredeemed Donations: <b><%= @unredeeemed_donations.count %></b></h5>
    <h5>Total Amount: <b>£<%= price.sum %></b></h5>
    <br>
    <p>Please select which donation you'd like to redeem from the dropdown below</p>
    <%= simple_form_for :items_redeemed, url: unredeemed_items_path, method: :get do |f| %>
      <%= f.input :donation_type, :collection => DonationType.order(:name), :prompt => "Choose a Donation To Redeem", label: false %>
      <%= f.submit "Redeem Donation", class: "btn-orange-rounded" %>
    <% end %>
  </div>
<% end %>