config/routes.rb
# require "stripe_event"
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users
  resources :users
  root to: "donation_types#index"
  get "about", to: "about#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :baskets, only: %i[show update create] do
    resources :payments, only: %i[new show]
    resources :basket_items, only: %i[create update destroy]
    # get :checkout, on: :member
  end
  get "/basket_items/unredeemed_items", to: "basket_items#unredeemed_items", as: "unredeemed_items"
  resources :charity_profiles do
    resources :donation_types
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show mr-1" style="margin-bottom: 80px;" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show mr-1" style="margin-bottom: 80px;" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-expand-sm navbar-gl" >
<!-- User Navbar - Signed In -->
    <% if user_signed_in? && !current_user.charity %>
      <%= link_to root_path(@root) do %>
        <li class="nav-item">
          <%= image_tag "HomeIcon.png", class: "nav-bar-icon-images" %>
        </li>
      <% end %>

      <div data-controller="basket-subscription"
        data-basket-subscription-basket-id-value="<%= session[:basket_id] %>">
        <div data-basket-subscription-target="basket">
        <%= render "basket_items/basket", basket: @basket %>
        </div>
      </div>

      <div data-bs-toggle="modal" data-bs-target="#exampleModal">
        <li class="nav-item">
          <%= image_tag "UserIcon.png", class: "nav-bar-icon-images" %>
        </li>
      </div>

<!-- Charity Navbar - Signed In -->
    <% elsif user_signed_in? && current_user.charity%>
      <%= link_to root_path(@root) do %>
        <li class="nav-item">
          <%= image_tag "HomeIcon.png", class: "nav-bar-icon-images" %>
        </li>
      <% end %>
      <%= link_to about_path(about_path) do %>
        <li class="nav-item">
          <%= image_tag "InfoIcon.png", class: "nav-bar-icon-images" %>
        </li>
      <% end %>

      <div data-bs-toggle="modal" data-bs-target="#exampleModal">
        <li class="nav-item">
          <%= image_tag "UserIcon.png", class: "nav-bar-icon-images" %>
        </li>
      </div>


<!-- User Navbar - Signed Out -->
    <% else %>
      <%= link_to root_path(@root) do %>
        <li class="nav-item">
          <%= image_tag "HomeIcon.png", class: "nav-bar-icon-images"%>
        </li>
      <% end %>
      <div data-controller="basket-subscription"
        data-basket-subscription-basket-id-value="<%= session[:basket_id] %>">
        <div data-basket-subscription-target="basket">
            <%= render "basket_items/basket", basket: @basket %>
        </div>
      </div>

      <div data-bs-toggle="modal" data-bs-target="#exampleModal">
        <li class="nav-item">
          <%= image_tag "UserIcon.png", class: "nav-bar-icon-images" %>
        </li>
      </div>
    <% end %>
</div>
<!-- Modal -->

<% if current_user %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
     <% if current_user.charity %>
      <%= link_to "My Dashboard", user_path(current_user), class: "btn-orange-rounded" %>
     <% else %>
      <%= link_to "My Profile", user_path(current_user), class: "btn-orange-rounded" %>
     <% end %>
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class: "btn-orange-rounded", style:"background-color: #EA5455;" %>
      </div>
    </div>
  </div>
</div>
<% else %>
  <% if current_user.nil? %>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= link_to "Login", new_user_session_path, class: "btn-orange-rounded" %>
          <%= link_to "Create Account", new_user_registration_path, class: "btn-orange-rounded" %>
        </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>